### ISSUE TITLE
Post-Feedback TODOs:

### ISSUE THREAD

**Issue by haldenl** [ParametricPress/02-streaming#10]
# Issues
- [x] Rerun data (last item: once rest of changes are in)
- [ ] Add instructions for running code in readme @ssshathi 
- [x] Fix sources for fb, goog, amzn, apple pledges for carbon free @mathisonian 
- [x] Check if deckgl has fixed flicker bug for safari in Big Sur 
- [x] (#22) Bolded text -> white? @anirmal1 @haldenl 
- [x] (#23) Copyright issues for album art?
- [x] Don't use caption for footnote? @anirmal1 
- [x] Remove margin from scrolly (above and below).
- [x] Double check code for data collection @haldenl @ssshathi 
- [x] Verify that songs fetch only the audio @ssshathi 
- [x] ~Get photo for fairchild factory?~ cant find one with license
- [x] (#21) Style graphic sources for mobile
- [x] (#20) Switch media picker preview to click instead of click + hold
- [x] Rewrite pledge paragraph
- [x] Typos (see slack thread
- [x] CO2 -> CO_2 
- [x] Pipeline emissions bar doesn't match up for cdns.
- [x] IMPORTANT: Fix video preloading (loading videos multiple times rn).

## Dragan's Feedback

- [x] (#11) Podcast vs Old Town Road = misleading. @anirmal1 @lilianliang
- [x] (#11) Video streaming similarly misleading. @anirmal1 @lilianliang 
- [x] (#13) Is meter driven by car meaningful? @haldenl

## Jane's Feedback
- [x] 'timeline breakdown of each title' -> title not the right word ('artifact' or 'type of media') instead? @anirmal1 
- [x] More space between name / bios for authors & end of article. @haldenl 
- [x] (#19) 'Case Study' -> Nice to talk a bit more about where this case study came from. @ssshathi 
- [x] I think it would help to have more context / explanation around the first Priest et al. estimate. For example: "Priest et al. estimate that the energy to run all of Google's data centers account for less than 2% of Youtube's total electricity use." @ssshathi 
- [x] "But their burden is still being felt today" -> burden to something else? @ssshathi 
- [x] (#12) Consider splitting last text bubble of pipeline into multiple with clearer points (slack thread has examples). @lilianliang
- [x] (#12) "YouTube's monthly active user count has since... [so the CO2 emissions are even higher...]" @lilianliang
- [x] (#14) Emissions of audio should have audio?
- [x] (#15) Have 360p + 1080p preview? Or make clear its just one
- [x] (#16) 'Sparkline' in Emissions of Video section to remind reader of emissions from earlier sections that are referenced.
- [x] (#17) Labeling may clarify the meaning of 4 lines in projection.
- [x] (#18) Can "YouTube (2016)" header fade in above corresponding bar? Instead of below.
- [x] "Belkhir and Elmeligi created two models to project the ICT sector's [emissions] decades forward"
- [x] "[enough to power] over half a million U.S. homes"
- [x] ~~Any way to less blur the facebook preview?~~ Privacy, so no.
- [x] ~~Pipeline map state borders are faint.~~. IMO this is fine.
- [x] ~~Media Emissions by Medium -> x axis labels at top too? (too tall).~~. I've removed the car equivalent text to make the vis a little shorter. Otherwise, I don't think putting the x axis labels on top provides too much value. The emissions of each bar are already labeled.

## Other feedback
- [x] Review

# Smaller Issues
- [x] "Components & Electricity Usage" -> Shorter title? (creates 2 lines on mobile).
- [x] (#23) Need to link websites / videos / audio?
- [x] Superfund map randomly resizes when scrolling? @haldenl 
- [x] [Mobile] Globe freezes when touched. @haldenl 
- [x] Scroller has awkward space steps between on mobile.
- [x] ~~Album art preview placement covers title.~~
- [x] Address caching for websites? Specify we used chrome?
- [x] [Mobile] Pipeline graphic overflows the viewport at stages? @haldenl
