### ISSUE TITLE
Fixes TODO

### ISSUE THREAD

**Issue by haldenl** [ParametricPress/02-streaming#9]
### General
- [x] Click to enable pan / zoom -> Enable / Disable
- [x] Trucks in first graphic don't show up on safari @haldenl 
- [x] Preload videos / images for media visualization @haldenl 
- [x] Add urls to all graphic sources @haldenl 
- [x] Add parametric preview @haldenl 
- [x] Animate first graphic? @haldenl 
- [x] Make deep passes over preview. Make sure text is good and everything is cited. @haldenl @lilianliang @anirmal1 @ssshathi 
- [x] ~~Add company logo in conclusion text~~ (permission issues here... quite strict on branding usage) @haldenl 
- [x] Move rewrite of last paragraph to preview (with sources) @ssshathi 
- [x] Some periods dont have spaces after them @ssshathi 
- [x] Better punchy description? (see slack discussion w/ Fred)
- [x] Add subhed to pipeline components @haldenl 
- [x] Record page for media emissions @haldenl @ssshathi 
- [x] Media picker autoplay gets interrupted by hover. @haldenl 
- [x] Switch modes -> Show Timeline / Hide Timeline @haldenl 
- [x] Cite google peering website for google cache storing more popular videos. @haldenl 
- [x] Car distance equivalent should read "Loading Facebook is equivalent ..." @haldenl 
- [x] Cite priest et al after each electricity info. @ssshathi 
- [x] Move last paragraph of pipeline to scroller (with no graphic?) To test how it looks @haldenl 
- [x] Remove periods in superfund map status @lilianliang 
- [x] Move google aside in conclusion (check location on mobile). @anirmal1 
- [x] Pipeline graphic shows grab / grabbing cursor.
- [x] Add sources/ titles to all graphics.
- [x] Add reference point for media picker emissions
- [x] Devices take into account lifecycle in Belkhir and Elmeligi but not in Priest et al?
- [x] Add sources for pipeline vis
- [x] Add caption / axis labels to pipeline line chart
- [x] Match text to reflect cropped pipeline graphic (reduced # of datacenters)
- [x] Can't hover over points in superfund map when zoom / drag is disabled.
- [x] Fix globe is cropped sometimes (add resize listener)
- [x] ~~Fix flicker on Safari for superfund map.~~ (looks like a beta only bug)
- [x] Crop pipeline graphic to exclude las vegas (there is a data center there)
- [x] Fix tooltip text colors or background in superfund map.
- [x] Window resize is slow.
- [x] Trucks are backwards
- [x] Make media picker interaction on hover for desktop
- [x] Pipeline text does not match graphic after removal of a step.
- [x] Video emissions title should read 'Emissions of Video'

### Mobile
- [x] Videos not autoplaying in safari ios
- [x] Try to move media emission parts further down in the section @anirmal1 
- [x] Change text that refers to visualizations (position) for media emissions section. @anirmal1 
- [x] Remove long touch action for media picker
- [x] Media picker hold not working 
- [x] Media picker timeline touch drag not working
- [ ] Pipeline graphic overflows the viewport at stages?
- [ ] Superfund map randomly resizes when scrolling?
- [x] Media emissions caption should change to tap & hold for touchscreens.
- [x] ~~Support globe rotate~~ (this would cause scroll jacking)
- [x] Fix superfund map zoom
- [x] Fix end of pipeline layout / text overlap (the view with the comparison between youtube and ict sector emissions)
- [x] Fix incorrect y translate for youtube graphic (causing "ICT Sector (2010)" text to appear during entire pipeline)
- [x] Fix scroll jacking on superfund map
